"""empty message

Revision ID: 10390d4b1bb9
Revises: 2aeffd957df5
Create Date: 2014-02-04 20:03:52.089636

"""

# revision identifiers, used by Alembic.
revision = '10390d4b1bb9'
down_revision = '2aeffd957df5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
