"""empty message

Revision ID: 14a2db81d1cc
Revises: bc003a85e36
Create Date: 2014-02-21 18:26:17.295800

"""

# revision identifiers, used by Alembic.
revision = '14a2db81d1cc'
down_revision = 'bc003a85e36'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bimlink',
    sa.Column('revit_id', sa.Integer(), nullable=False),
    sa.Column('excel_id', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('revit_id'),
    sa.UniqueConstraint('excel_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bimlink')
    ### end Alembic commands ###
