"""empty message

Revision ID: 1576a8113dd3
Revises: 404f862c2942
Create Date: 2014-01-28 22:23:33.929088

"""

# revision identifiers, used by Alembic.
revision = '1576a8113dd3'
down_revision = '404f862c2942'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
