"""empty message

Revision ID: 1bedae6714a4
Revises: 456d8230bcf1
Create Date: 2014-02-14 20:39:15.982422

"""

# revision identifiers, used by Alembic.
revision = '1bedae6714a4'
down_revision = '456d8230bcf1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
