"""empty message

Revision ID: 1f3e442d59b5
Revises: 2d0963bc622e
Create Date: 2014-01-28 16:55:29.936808

"""

# revision identifiers, used by Alembic.
revision = '1f3e442d59b5'
down_revision = '2d0963bc622e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
