"""empty message

Revision ID: 20ab8d2311ae
Revises: 35e1815fcc64
Create Date: 2014-02-13 17:07:21.039285

"""

# revision identifiers, used by Alembic.
revision = '20ab8d2311ae'
down_revision = '35e1815fcc64'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bimimage', sa.Column('report_type', sa.String(length=60), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bimimage', 'report_type')
    ### end Alembic commands ###
