"""empty message

Revision ID: 2293d45986e5
Revises: 275620408454
Create Date: 2014-01-28 22:02:04.945645

"""

# revision identifiers, used by Alembic.
revision = '2293d45986e5'
down_revision = '275620408454'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
