"""empty message

Revision ID: 22ee37bebfb6
Revises: fb5eaaa37d6
Create Date: 2014-02-11 16:08:30.775954

"""

# revision identifiers, used by Alembic.
revision = '22ee37bebfb6'
down_revision = 'fb5eaaa37d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bimlink',
    sa.Column('revit_id', sa.Integer(), nullable=False),
    sa.Column('excel_id', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('revit_id'),
    sa.UniqueConstraint('excel_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bimlink')
    ### end Alembic commands ###
