"""empty message

Revision ID: 275620408454
Revises: 4d3229babb84
Create Date: 2014-01-28 20:17:46.903509

"""

# revision identifiers, used by Alembic.
revision = '275620408454'
down_revision = '4d3229babb84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
