"""empty message

Revision ID: 30e372e6f98
Revises: 14a2db81d1cc
Create Date: 2014-02-21 22:51:45.880104

"""

# revision identifiers, used by Alembic.
revision = '30e372e6f98'
down_revision = '14a2db81d1cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', u'foreman')
    op.drop_column('track', u'supervisor')
    op.drop_column('track', u'laborer')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column(u'laborer', sa.INTEGER(), nullable=True))
    op.add_column('track', sa.Column(u'supervisor', sa.INTEGER(), nullable=True))
    op.add_column('track', sa.Column(u'foreman', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
