"""empty message

Revision ID: 354c930f4593
Revises: e93fc44385f
Create Date: 2014-01-29 16:45:28.549380

"""

# revision identifiers, used by Alembic.
revision = '354c930f4593'
down_revision = 'e93fc44385f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift', sa.String(length=1), nullable=True),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material', sa.String(length=8), nullable=True),
    sa.Column('unit', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material')
    )
    op.add_column(u'track', sa.Column('foreman', sa.Integer(), nullable=True))
    op.add_column(u'track', sa.Column('laborer', sa.Integer(), nullable=True))
    op.add_column(u'track', sa.Column('material_id', sa.Integer(), nullable=True))
    op.add_column(u'track', sa.Column('shift_id', sa.Integer(), nullable=True))
    op.add_column(u'track', sa.Column('supervisor', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'track', 'supervisor')
    op.drop_column(u'track', 'shift_id')
    op.drop_column(u'track', 'material_id')
    op.drop_column(u'track', 'laborer')
    op.drop_column(u'track', 'foreman')
    op.drop_table('material')
    op.drop_table('shift')
    ### end Alembic commands ###
