"""empty message

Revision ID: 35e1815fcc64
Revises: 43bca9824968
Create Date: 2014-02-12 22:26:35.927498

"""

# revision identifiers, used by Alembic.
revision = '35e1815fcc64'
down_revision = '43bca9824968'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
