"""empty message

Revision ID: 404f862c2942
Revises: 2293d45986e5
Create Date: 2014-01-28 22:07:49.837295

"""

# revision identifiers, used by Alembic.
revision = '404f862c2942'
down_revision = '2293d45986e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
