"""empty message

Revision ID: 43bca9824968
Revises: 22d04423fce
Create Date: 2014-02-12 22:03:41.021532

"""

# revision identifiers, used by Alembic.
revision = '43bca9824968'
down_revision = '22d04423fce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
