"""empty message

Revision ID: 45aadf241d30
Revises: 28567d02973e
Create Date: 2014-02-25 22:45:38.645452

"""

# revision identifiers, used by Alembic.
revision = '45aadf241d30'
down_revision = '28567d02973e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('img_filename', sa.String(length=200), nullable=True),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table(u'bimimage')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'bimimage',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'img_filename', sa.VARCHAR(length=60), nullable=True),
    sa.Column(u'report_date', sa.DATE(), nullable=True),
    sa.Column(u'report_type', sa.VARCHAR(length=60), nullable=True),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.drop_table('daily')
    ### end Alembic commands ###
