"""empty message

Revision ID: 4d3229babb84
Revises: 1f3e442d59b5
Create Date: 2014-01-28 19:57:44.517030

"""

# revision identifiers, used by Alembic.
revision = '4d3229babb84'
down_revision = '1f3e442d59b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
