"""empty message

Revision ID: 4fbff05e985b
Revises: 23e1e5e4c7ab
Create Date: 2014-02-06 15:30:01.376242

"""

# revision identifiers, used by Alembic.
revision = '4fbff05e985b'
down_revision = '23e1e5e4c7ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
