"""empty message

Revision ID: e93fc44385f
Revises: 1576a8113dd3
Create Date: 2014-01-28 22:30:00.563511

"""

# revision identifiers, used by Alembic.
revision = 'e93fc44385f'
down_revision = '1576a8113dd3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
