"""empty message

Revision ID: fb5eaaa37d6
Revises: 4fbff05e985b
Create Date: 2014-02-06 15:58:59.097712

"""

# revision identifiers, used by Alembic.
revision = 'fb5eaaa37d6'
down_revision = '4fbff05e985b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'users',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'firstname', sa.VARCHAR(length=100), nullable=True),
    sa.Column(u'lastname', sa.VARCHAR(length=100), nullable=True),
    sa.Column(u'email', sa.VARCHAR(length=120), nullable=True),
    sa.Column(u'password', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint(u'id')
    )
    ### end Alembic commands ###
